export function generateFeedback(answer) {
    const lowerCaseAnswer = answer.toLowerCase()

    const rubric = [
        {
            title: 'Staffing Readiness',
            points: 20,
            keywords: ['staff', 'staffing', 'personnel', 'nurse', 'nursing'],
        },
        {
            title: 'Patient Monitoring',
            points: 20,
            keywords: ['monitor', 'monitoring', 'observation', 'follow-up'],
        },
        {
            title: 'CRS Management',
            points: 20,
            keywords: ['crs', 'cytokine release syndrome', 'escalation'],
        },
        {
            title: 'Protocol Readiness',
            points: 20,
            keywords: ['protocol', 'workflow', 'procedure'],
        },
        {
            title: 'Pharmacy Readiness',
            points: 20,
            keywords: ['pharmacy', 'pharmacist', 'medication'],
        },
    ]

    let score = 0
    const strengths = []
    const improvements = []

    rubric.forEach((category) => {
        const matched = category.keywords.some((keyword) =>
            lowerCaseAnswer.includes(keyword),
        )

        if (matched) {
            score += category.points
            strengths.push(`Addressed ${category.title}`)
        } else {
            improvements.push(`Consider discussing ${category.title}`)
        }
    })

    return {
        score,
        strengths,
        improvements,
        message: 'Feedback generated by the backend scoring service.',
    }
}